### ISSUE TITLE
Reset openai-key

### ISSUE THREAD

**Issue by heijligers** [eliranwong/letmedoit#22] opened 2024-01-03 15:33 UTC
I believe I might have made a typo when entering my openai api key. how do I reset it from the command line?
I keep getting:
`letmedoit 
Error: Issue on OpenAI side.
Solution: Retry your request after a brief wait and contact us if the issue persists.
launching LetMeDoIt AI ...`

**Comment by heijligers** [comment] 2024-01-03 15:45
hmmm I have found:
'HealthCheck.changeAPIkey()'
now i'm getting
'OpenAI API returned an API Error: Connection error.'

**Comment by heijligers** [comment] 2024-01-03 16:01
so resetting doesn't seem to work.. 
I found the config.py in the venv path and edited it manually.

Issue remains open regarding 
'.openaiAPIKeyChange'
and 
'HealthChange.changeApikey()'
both not working when a wrong api key has been entered

**Comment by eliranwong** [comment] 2024-01-03 18:03
May I ask if the issue is sorted yet?

Does the letmedoit app start as expected?  You can enter a blank entry and select to change to api key.

It should work fine.

Just few points to mention:

* if you manually edit the "config.py" file, please first make sure the app is closed.

* one of users reported previously that he cannot connect to the openai server as expected, but after he enter billing information to his openai account, connection works fine.

I am not sure if these relevant to you.

**Comment by eliranwong** [comment] 2024-01-06 17:54
I assume the issue was sorted.  Please kindly let me know if not.  I am closing this issue first.

**Closed by eliranwong** 2024-01-06 17:54 UTC
